language: c

matrix:
  include:
    - os: linux
      env: TARGET="linux"

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: build/mbc*
  skip_cleanup: true

branches:
  only:
    - master

install:
  - echo "nothing to do"

script:
  - sh build.sh
